feat(pg-typed): route queries to primary or replica connections
ForbesLindesay/atdatabases pull request #198
Opened 2021-11-03 12:59 UTC by avaly

Closes #197

This PR adds support for primary/replicas query routing in `pg-typed`.

The unit test for this new feature is not using a primary+replica pg cluster, since it's more complex to setup in this testing environment, but I simulated having the primary connection closed while running read queries on the secondary connection.

2021-11-15 12:58 UTC, ForbesLindesay requested changes
The error message should just request a single connection.

2021-11-15 12:58 UTC, ForbesLindesay commented on packages/pg-typed/src/index.ts
> +        'You must either provide a "defaultConnection" to pg-typed, or specify a list of connections when accessing the table.',
The list of connections approach is still an advanced use case, so the error should still only tell you about the missing connection.

```suggestion
        'You must either provide a "defaultConnection" to pg-typed, or specify a connection when accessing the table.',
```

2021-11-15 12:58 UTC, ForbesLindesay commented on packages/pg-typed/src/__tests__/index.test.pg.ts
> +    `"You must either provide a \\"defaultConnection\\" to pg-typed, or specify a list of connections when accessing the table."`,
```suggestion
    `"You must either provide a \\"defaultConnection\\" to pg-typed, or specify a connection when accessing the table."`,
```

2021-11-15 13:16 UTC, ForbesLindesay commented
Thank you for this contribution. Having thought a bit more about it, I think it may be better to handle this at the Postgres client level, rather than only for these high level typed interfaces. We could have a package for `@databases/pg-replica` that takes `{primary: Queryable, replicas: readonly Queryable[]}` and returns `Queryable`. See:

https://github.com/ForbesLindesay/atdatabases/blob/3291185bfb8942bba22090be578d2215df1bb6f7/packages/pg/src/types/Queryable.ts#L7-L29

We could automatically select the readonly replicas for transactions where `readOnly: true` is passed:

https://github.com/ForbesLindesay/atdatabases/blob/3291185bfb8942bba22090be578d2215df1bb6f7/packages/pg/src/types/TransactionOptions.ts#L16

We could also automatically select the readonly replica for queries that start match `/^select\b/i`

2021-11-15 14:48 UTC, avaly commented
I like your idea with the `pg-replica` package @ForbesLindesay. I can open a PR for that soon.

2022-04-22 10:21 UTC, avaly commented
Super seeded by #240

2022-04-22 10:21 UTC, closed without merging